# sample config

data_root: /home/ubuntu/

modality: audio

exp:
    wandb: true
    wandb_api_key: 
    proj_name: data2vec_KWS
    exp_dir: ./runs
    exp_name: data2vec_kwt1_27092022
    device: auto
    log_freq: 20    # log every l_f steps
    log_to_file: True
    log_to_stdout: True
    val_freq: 5    # validate every v_f epochs
    n_workers: 1
    pin_memory: True
    cache: 0 # 0 -> no cache | 1 -> cache wavs | 2 -> cache specs; stops wav augments
    

hparams:
    seed: 0
    batch_size: 512
    n_epochs: 200
    device: "cuda"
    loss_beta: 2

    audio:
        sr: 16000
        n_mels: 40
        n_fft: 480
        win_length: 480
        hop_length: 160
        center: False
    
    model:
        name: kwt-1 # if name is provided below settings will be ignored during model creation
        dim: 64
        ema_decay: 0.999
        ema_end_decay: 0.9999
        ema_anneal_end_step: 1000
        average_top_k_layers: 8
        normalize_targets: true
        mask_prob: 0.65
        mask_length: 10
        min_masks: 1

    optimizer:
        opt_type: adam
        opt_kwargs:
          lr: 0.0005
          weight_decay: 0.01
          betas: !!python/tuple [0.9, 0.98]
          eps: 0.000001
    
    scheduler:
        n_warmup: 0
        max_epochs: 200
        scheduler_type: cosine_annealing

    augment:
            #        resample:
            #r_min: 0.85
            #r_max: 1.15
        
            #time_shift:
            #s_min: -0.1
            #s_max: 0.1

            #bg_noise:
            #bg_folder: /home/ubuntu/GoogleSpeechCommands/speech_commands_v0.02/_background_noise_/

        # spec_aug:
        #     n_time_masks: 2
        #     time_mask_width: 25
        #     n_freq_masks: 2
        #     freq_mask_width: 7
